### ISSUE TITLE
Genesis json compatible with original Dogechain

### ISSUE THREAD

**Issue by DarianShawn** [dogechain-lab/dbsc#2]
The DC (Dogechain) `genesis.json` already used for a long time, and its hash is determined, but not accepted by dbsc (Dogechain BSC). So the node couldn't recognize it.

We could translation it manually, for fast testing. But a new tool is also needed to cover its generation.

**Comment by DarianShawn** [comment]
#3  for genesis and consensus compatible.

**Comment by DarianShawn** [comment]
@0xcb9ff9 Here is my opinion.
Since the contract repository is not public viewed and the git commits might not be found in current contract repo (modified 
 and migrated to new organization and new repository twice).
I would suggest that using [dogechain v1](https://github.com/dogechain-lab/dogechain) to generate a compatible genesis file instead of building another tool. How about that?

**Comment by 0xcb9ff9** [comment]
PR #8 has genesis information embedded in the code, maybe we just need to provide a tool to create genesis.json ? (provide different chain id, hard fork, ibft configuration)

**Comment by DarianShawn** [comment]
Alright, a new command is a good idea.

**Comment by DarianShawn** [comment]
Done and close.
