### ISSUE TITLE
How to run a node with pre-v2 chaindata?

### ISSUE THREAD

**Issue by ircrp** [dogechain-lab/dbsc#54]
If I've been operating a node using a pre-version 2 release and have collected chaindata up to block 0x1219e62 (18980450), what are the precise steps to transfer this data to make it compatible with the version 2 release?

**Comment by DarianShawn** [comment]
Check it out with documentation on [Tutorials](https://docs.dogechain.dog/docs/get-started/tutorials) and [Run full node](https://docs.dogechain.dog/docs/get-started/full-node-deployment).

**Comment by ircrp** [comment]
Hello @DarianShawn, I checked the documentation but didn't find instructions on migrating pre-v2 chaindata to v2. The recommended 1.8 TB snapshot download isn't feasible for me due to hardware constraints. Is there a way to use my existing chaindata with version 2, and if so, could you provide or direct me to the necessary steps? Thank you!

**Comment by DarianShawn** [comment]
You could wait for the next release of pruned snapshot.
It is small and up to day with v2 data.

**Comment by 0xcb9ff9** [comment]
@ircrp  pruned snapshot is upload  https://github.com/dogechain-lab/dogechain-snapshots#pruned-ancient-database

**Comment by ircrp** [comment]
Thanks, that worked
