### ISSUE TITLE
my mainnet node is not syncing is showing `looking for peers` 

### ISSUE THREAD

**Issue by Supra-RaghulRajeshR** [dogechain-lab/dbsc#56]
Hello i have upgraded my mainnet node from the v1 to v2  and i downloaded the latest snapshot also, still it is throwing logs like `Nov 03 07:13:21 dogechain-mainnet-node1-2 geth[2283806]: INFO [11-03|07:13:21.988] Looking for peers                        peercount=0 tried=40 static=0`

**Comment by 0xcb9ff9** [comment]
try add [bootnodes](https://docs.dogechain.dog/docs/get-started/bootnode-list) ?

**Comment by Supra-RaghulRajeshR** [comment]
yes i used even it is not syncing

**Comment by Supra-RaghulRajeshR** [comment]
@0xcb9ff9 i have added both the enode from the this [blog](https://docs.dogechain.dog/docs/get-started/full-node-deployment#create-systemd-service) and this [blog](https://docs.dogechain.dog/docs/get-started/bootnode-list#mainnet) also it is not worked.

`Nov 03 09:45:45 dogechain-mainnet-node1-2 geth[2284733]: INFO [11-03|09:45:45.977] Looking for peers                        peercount=0 tried=50 static=0
Nov 03 09:45:56 dogechain-mainnet-node1-2 geth[2284733]: INFO [11-03|09:45:56.013] Looking for peers                        peercount=0 tried=39 static=0
Nov 03 09:46:06 dogechain-mainnet-node1-2 geth[2284733]: INFO [11-03|09:46:06.013] Looking for peers                        peercount=0 tried=33 static=0
Nov 03 09:46:16 dogechain-mainnet-node1-2 geth[2284733]: INFO [11-03|09:46:16.038] Looking for peers                        peercount=0 tried=39 static=0
Nov 03 09:46:26 dogechain-mainnet-node1-2 geth[2284733]: INFO [11-03|09:46:26.346] Looking for peers                        peercount=0 tried=39 static=0
Nov 03 09:46:36 dogechain-mainnet-node1-2 geth[2284733]: INFO [11-03|09:46:36.346] Looking for peers                        peercount=1 tried=43 static=0
Nov 03 09:46:46 dogechain-mainnet-node1-2 geth[2284733]: INFO [11-03|09:46:46.682] Looking for peers                        peercount=1 tried=38 static=0
Nov 03 09:46:56 dogechain-mainnet-node1-2 geth[2284733]: INFO [11-03|09:46:56.761] Looking for peers                        peercount=1 tried=36 static=0
Nov 03 09:47:06 dogechain-mainnet-node1-2 geth[2284733]: INFO [11-03|09:47:06.927] Looking for peers                        peercount=0 tried=42 static=0
Nov 03 09:47:17 dogechain-mainnet-node1-2 geth[2284733]: INFO [11-03|09:47:17.012] Looking for peers                        peercount=0 tried=35 static=0
Nov 03 09:47:27 dogechain-mainnet-node1-2 geth[2284733]: INFO [11-03|09:47:27.012] Looking for peers                        peercount=0 tried=41 static=0
`

**Comment by 0xcb9ff9** [comment]
genesis.json ?
[very important key point](https://docs.dogechain.dog/docs/get-started/hawaii-hard-fork#upgrade-guide)

**Comment by Supra-RaghulRajeshR** [comment]
@0xcb9ff9 using `genesis-after-hawaii.json` as a genesis.json

**Comment by 0xcb9ff9** [comment]
check block height ? if less 18980450 need use `genesis-before-hawaii.json` and [static-nodes.json](https://docs.dogechain.dog/assets/files/static-nodes-d4262ad04f9085a17e65170e56d01ada.json) connect to deprecated bootnodes 

https://docs.dogechain.dog/docs/get-started/full-node-deployment#copy-genesisjson-to-etc-directory

**Comment by 0xcb9ff9** [comment]
@Supra-RaghulRajeshR  [pruned snapshot](https://github.com/dogechain-lab/dogechain-snapshots#pruned-ancient-database) now update, this after `Hawaii Fork`

**Comment by Supra-RaghulRajeshR** [comment]
@0xcb9ff9  so if i downloaded this snapshot  and can use this `genesis-after-hawaii.json ` for genensis.json?

**Comment by 0xcb9ff9** [comment]
@Supra-RaghulRajeshR  yes

**Comment by Supra-RaghulRajeshR** [comment]
i will try and let you know thanks

**Comment by Supra-RaghulRajeshR** [comment]
@0xcb9ff9  pls check this one.

the snapshot is not authorised to download
`403 Forbidden
Code: AccessDenied
Message: Access Denied
RequestId: PWNC0FGQACAKKGGF
HostId: WMBVZv8FDv99kc8VQUr5B9DCxugIusV22cLGS1Nl6e16lDTuUKgGND1Cd6qU2v3HmfzRgy0XeoY=`

**Comment by 0xcb9ff9** [comment]
@Supra-RaghulRajeshR  please download snapshot file [dbsc.2023-11-02T00_33_31-UTC.snapshot.zst](https://snapshots.dogechaindev.com/dbsc.2023-11-02T00_33_31-UTC.snapshot.zst), 
**don't download** [dbsc.2023-10-19T02_55_20-UTC.snapshot.zst](http://snapshots.dogechain.dog/dbsc.2023-10-19T02_55_20-UTC.snapshot.zst)

**Comment by Supra-RaghulRajeshR** [comment]
@0xcb9ff9 thanks

**Comment by Supra-RaghulRajeshR** [comment]
@0xcb9ff9  for testnet can you prefer me any genesis link?

**Comment by Supra-RaghulRajeshR** [comment]
any snapshot for the testnet?

**Comment by 0xcb9ff9** [comment]
@Supra-RaghulRajeshR  genesis is here [releases](https://github.com/dogechain-lab/dbsc/releases/tag/v2.0.2), testnet redeployed, don't need snapshot

**Comment by Supra-RaghulRajeshR** [comment]
@0xcb9ff9  sorry to bother again, it is also saying that the `looking for peers` and i deleted all and started from the scratch. used the bootnodes from the blog you provided it is having for testnet also. am i missing anything here?

**Comment by DarianShawn** [comment]
> @0xcb9ff9 sorry to bother again, it is also saying that the `looking for peers` and i deleted all and started from the scratch. used the bootnodes from the blog you provided it is having for testnet also. am i missing anything here?

Testnet needs to set `--networkid=568`.
It should work. I've just tried.

**Comment by Supra-RaghulRajeshR** [comment]
@DarianShawn  Thanks it worked

**Comment by ericcheng201168** [comment]
I got the same issue on mainnet. 
- Updated to 2.0.3 client
- Downloaded latest snapshot from https://github.com/dogechain-lab/dogechain-snapshots
- startup command:
geth --cache 24000 --syncmode snap --datadir node_data --rpc.allow-unprotected-txs --txlookuplimit 0 --tries-verify-mode none -bootnodes "enode://38bd46ce29743660e236db29f50e049d3973c93cea835effc4f3cc642aab4e80baf9960906adb742ff676e0047b332f112cf723864d07c87319a277bf420ccbe@44.207.147.216:30303,enode://c2d67c2fc2bd060a77bc850430a87fd8847d689302f6447c1cfef1422e2d0d91607574d4a7707ca57c20c4ecc94b0561653f5ade5ed15065954479fcbb306eee@54.210.49.16:30303" --genesis=mainnet/genesis-after-hawaii.json --gcmode=full --txpool.pricelimit=250000000000 --miner.gasprice=250000000000 --miner.gaslimit=300000000

<img width="1027" alt="image" src="https://github.com/dogechain-lab/dbsc/assets/10498162/67e794d3-4b3e-481f-9c73-b209c9e847ff">

**Comment by 0xcb9ff9** [comment]
> I got the same issue on mainnet.
> 
>     * Updated to 2.0.3 client
> 
>     * Downloaded latest snapshot from https://github.com/dogechain-lab/dogechain-snapshots
> 
>     * startup command:
>       geth --cache 24000 --syncmode snap --datadir node_data --rpc.allow-unprotected-txs --txlookuplimit 0 --tries-verify-mode none -bootnodes "enode://38bd46ce29743660e236db29f50e049d3973c93cea835effc4f3cc642aab4e80baf9960906adb742ff676e0047b332f112cf723864d07c87319a277bf420ccbe@44.207.147.216:30303,enode://c2d67c2fc2bd060a77bc850430a87fd8847d689302f6447c1cfef1422e2d0d91607574d4a7707ca57c20c4ecc94b0561653f5ade5ed15065954479fcbb306eee@54.210.49.16:30303" --genesis=mainnet/genesis-after-hawaii.json --gcmode=full --txpool.pricelimit=250000000000 --miner.gasprice=250000000000 --miner.gaslimit=300000000
> 
> 
> <img alt="image" width="1027" src="https://user-images.githubusercontent.com/10498162/280504410-67e794d3-4b3e-481f-9c73-b209c9e847ff.png">

Mainnet needs to set `--networkid=2000`.

**Comment by 0xcb9ff9** [comment]
@ericcheng201168  Use full sync mode please. snap mode exist issue #59

**Comment by 0xcb9ff9** [comment]
> @ericcheng201168 Use full sync mode please. snap mode exist issue #59

@Supra-RaghulRajeshR

**Comment by ericcheng201168** [comment]
@0xcb9ff9 
It works after I set the chain id to 2000, thanks!

**Comment by Supra-RaghulRajeshR** [comment]
@0xcb9ff9  the mainnet node is stoped at block height `19098153` and the logs are

`Nov 06 05:11:56 dogechain-mainnet-node1-2 geth[2324041]: INFO [11-06|05:11:56.394] Importing heavy sidechain segment        blocks=2048 start=19,126,826 end=19,128,873
Nov 06 05:11:59 dogechain-mainnet-node1-2 geth[2324041]: INFO [11-06|05:11:59.424] Imported new chain segment               blocks=2048 txs=2117 mgas=102.811 elapsed=3.029s mgasps=33.936 number=19,128,873 hash=1fa15a..dc0e05 age=1d13h30m dirty=57.77MiB
Nov 06 05:11:59 dogechain-mainnet-node1-2 geth[2324041]: INFO [11-06|05:11:59.476] Importing heavy sidechain segment        blocks=2048 start=19,128,874 end=19,130,921
Nov 06 05:12:00 dogechain-mainnet-node1-2 geth[2324041]: INFO [11-06|05:12:00.058] Looking for peers                        peercount=3 tried=31  static=0
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]: panic: runtime error: invalid memory address or nil pointer dereference
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd87267]
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]: goroutine 2559 [running]:
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]: github.com/ethereum/go-ethereum/core/vm.opRandom(0xc02228b9e0?, 0xc01cb1c460?, 0xc037b5f608)
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]:         github.com/ethereum/go-ethereum/core/vm/instructions.go:488 +0x47
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]: github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc01cb1c460, 0xc019a9b380, {0xc03db3aa40, 0x24, 0x40}, 0x0)
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]:         github.com/ethereum/go-ethereum/core/vm/interpreter.go:253 +0x92d
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]: github.com/ethereum/go-ethereum/core/vm.(*EVM).Call(0xc02228b9e0, {0x2c69b60, 0xc019a9b2c0}, {0x54, 0x48, 0x70, 0xcc, 0x7f, 0xf9, 0x4a, ...}, ...)
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]:         github.com/ethereum/go-ethereum/core/vm/evm.go:249 +0xc1b
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]: github.com/ethereum/go-ethereum/core/vm.opCall(0xc02228b9e0?, 0xc01cb1c460, 0xc037b5f368)
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]:         github.com/ethereum/go-ethereum/core/vm/instructions.go:702 +0x633
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]: github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc01cb1c460, 0xc019a9b2c0, {0xc027970030, 0x24, 0x24}, 0x0)
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]:         github.com/ethereum/go-ethereum/core/vm/interpreter.go:253 +0x92d
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]: github.com/ethereum/go-ethereum/core/vm.(*EVM).Call(0xc02228b9e0, {0x2c6ed00, 0xc03215fcb0}, {0x47, 0x43, 0x96, 0x4a, 0xde, 0x62, 0xf1, ...}, ...)
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]:         github.com/ethereum/go-ethereum/core/vm/evm.go:249 +0xc1b
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]: github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0xc0222c5700)
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]:         github.com/ethereum/go-ethereum/core/state_transition.go:346 +0x8d9
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]: github.com/ethereum/go-ethereum/core.ApplyMessage(0x2272960?, {0x2c97510?, 0xc0277b8120?}, 0xc03a7e35e0?)
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]:         github.com/ethereum/go-ethereum/core/state_transition.go:184 +0x2a
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]: github.com/ethereum/go-ethereum/core.applyTransaction({0xc03215fb48, {0xcf, 0x48, 0xa5, 0x9e, 0xfe, 0xb2, 0x16, 0xc6, 0xab, ...}, ...}, ...)
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]:         github.com/ethereum/go-ethereum/core/state_processor.go:475 +0x1c6
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]: github.com/ethereum/go-ethereum/core.(*StateProcessor).Process(0xc000e44660, 0xc01b28e800, 0xc01d1c4000, {0x0, {0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, ...})
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]:         github.com/ethereum/go-ethereum/core/state_processor.go:447 +0x1119
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]: github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc005a66000, {0xc02cc5e000?, 0x800, 0xa00}, 0x0, 0x1)
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]:         github.com/ethereum/go-ethereum/core/blockchain.go:1928 +0x1f06
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]: github.com/ethereum/go-ethereum/core.(*BlockChain).insertSideChain(0xc005a66000, 0x249c2ea?, 0xc0039f7508)
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]:         github.com/ethereum/go-ethereum/core/blockchain.go:2203 +0x1acc
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]: github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc005a66000, {0xc0313eb378?, 0x1, 0x1}, 0x1, 0x1)
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]:         github.com/ethereum/go-ethereum/core/blockchain.go:1797 +0xad2
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]: github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc005a66000, {0xc0313eb378?, 0x1, 0x1})
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]:         github.com/ethereum/go-ethereum/core/blockchain.go:1695 +0xb51
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]: github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).importBlockResults(0xc00b27ab00, {0xc0313eb370, 0x1, 0x0?})
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]:         github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1463 +0x47d
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]: github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent(0xc00b27ab00)
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]:         github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1432 +0xaf
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]: github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1()
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]:         github.com/ethereum/go-ethereum/eth/downloader/downloader.go:628 +0x70
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]: created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
Nov 06 05:12:01 dogechain-mainnet-node1-2 geth[2324041]:         github.com/ethereum/go-ethereum/eth/downloader/downloader.go:628 +0x5f
Nov 06 05:12:01 dogechain-mainnet-node1-2 systemd[1]: dbsc.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 06 05:12:01 dogechain-mainnet-node1-2 systemd[1]: dbsc.service: Failed with result 'exit-code'.`

**Comment by 0xcb9ff9** [comment]
@Supra-RaghulRajeshR  use [v2.0.3](https://github.com/dogechain-lab/dbsc/releases/tag/v2.0.3), PR: #58

**Comment by Supra-RaghulRajeshR** [comment]
@0xcb9ff9 any snapshot for the testnet?

**Comment by 0xcb9ff9** [comment]
@Supra-RaghulRajeshR  No, the `testnet` is not creating snapshot right now

**Comment by Supra-RaghulRajeshR** [comment]
@0xcb9ff9  okay thanks

**Comment by Supra-RaghulRajeshR** [comment]
Hello @0xcb9ff9  my testnet is not synced yet, the block height between my node is `16773193`. without snapshot it is really taking too long time. pls help me with this.

**Comment by 0xcb9ff9** [comment]
@Supra-RaghulRajeshR  testnet has re-deployed, you need to resynchronize, use this genesis
https://github.com/dogechain-lab/dbsc/releases/download/v2.0.2/testnet.zip

**Comment by Supra-RaghulRajeshR** [comment]
okay thanks
